<?php

namespace Crumbls\Importer;

use Crumbls\Importer\Console\ImporterCommand;
use Crumbls\Importer\Console\InstallCommand;
use Crumbls\Importer\Console\SimpleTuiDemo;
use Crumbls\Importer\Console\InteractiveTuiDemo;
use Crumbls\Importer\Events\ImportServiceInitialized;
use Crumbls\Importer\Events\StorageServiceInitialized;
use Crumbls\Importer\Listeners\RegisterImportDrivers;
use Crumbls\Importer\Listeners\RegisterStorageDrivers;
use Crumbls\Importer\Services\ImportService;
use Crumbls\Importer\Services\StorageService;
use Illuminate\Support\Facades\Event;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class ImporterServiceProvider extends PackageServiceProvider
{
    public function configurePackage(Package $package): void
    {
        $package
            ->name('importer')
            ->hasConfigFile()
            ->hasViews()
            ->hasMigrations([
                'create_imports_table',
                'create_import_model_maps_table'
            ]);
    }

    public function boot()
    {
        $this->loadViewsFrom(__DIR__.'/../resources/views', 'crumbls-importer');
        $this->loadTranslationsFrom(__DIR__.'/../resources/lang', 'crumbls-importer');
        
        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__.'/../resources/views' => resource_path('views/vendor/crumbls-importer'),
            ], 'crumbls-importer-views');
            
            $this->publishes([
                __DIR__.'/../resources/lang' => resource_path('lang/vendor/crumbls-importer'),
            ], 'crumbls-importer-translations');
        }
    }

	public function packageBooted()
	{
		parent::packageBooted(); // TODO: Change the autogenerated stub

		// Load migrations
		$this->loadMigrationsFrom(__DIR__ . '/../database/migrations');

		// Register event listener for driver registration
		Event::listen(ImportServiceInitialized::class, RegisterImportDrivers::class);
		Event::listen(StorageServiceInitialized::class, RegisterStorageDrivers::class);

		if ($this->app->runningInConsole()) {
			$this->commands([
				ImporterCommand::class,
				InstallCommand::class,
			]);
		}
	}

	public function packageRegistered() : void {
		parent::packageRegistered();

		$this->app->singleton(ImportService::class, function ($app) {
			return new ImportService($app);
		});

		$this->app->alias(ImportService::class, 'importer');


		$this->app->singleton(StorageService::class, function ($app) {
			return new StorageService($app);
		});

		$this->app->alias(StorageService::class, 'importer-storage');
	}

}